### ISSUE TITLE
Visual acceptance is not showing new images captured when new commits are pushed

### ISSUE THREAD

**Issue by rox163** [ciena-blueplanet/ember-cli-visual-acceptance#90] opened 2016-08-29 19:58 UTC
Visual acceptance commented and added new images to my PR on first opening it 👍  I pushed another commit and then it edited it's existing comment and removed the images, marking it as No changes 👎 
Maybe it should add a new comment instead because we want the new images to remain there as examples of new UIs

**Comment by dafortin** [comment] 2016-09-19 16:53
The expectation is that we should have only one comment from `Visual Acceptance Test` in a PR and it should always be the diff. between the current merged baseline and the last commit pushed.

Here it seems like the the diff. is between the last commit pushed and the previous commit pushed.

**Comment by dafortin** [comment] 2016-09-20 12:14
After a quick analysis, we noticed that the problem is occurring when there is multiple jobs in the same travis build. We have one comment in the PR that we should be editing, but there is multiple build results. We are changing the comment in the PR with the latest result that we are getting from all the jobs.

So for example if we have the following sequence:
1. Job passed -> new changes
2. Job failed -> no changes
3. Job passed -> new changes
4. Job failed -> no changes

We will end up with `no changes` since that's the last time we are editing the comment in the PR.

We have 2 solutions to propose:
1. Add a variable to only get the result from a specific job for example `--msg-on='default' --msg-var=$EMBER_TRY_SCENARIO`
2. Create a comment in the PR for every job in the build to avoid this overlap

I will personally recommend the first approach for the following reason:
1. We are expecting that the result of all the jobs should be the same (same capture)
2. It will avoid adding too many comments in the PR.
3. It a simpler approach.

**Comment by dafortin** [comment] 2016-09-20 18:35
After discussion with @sglanzer and @EWhite613, we decided to implement the first solution described above.

**Comment by dafortin** [comment] 2016-09-21 19:53
Tested on frost-modal and I'm not able to reproduce the problem.

**Closed by dafortin** 2016-09-21 19:53 UTC
Labels: bug
